dist: xenial
sudo: false
language: java
if: tag is blank

# Note: Travis generally does not allocate more than 5 VMs at once.
# Avoid running more than 5 jobs in parallel. Try to keep the jobs
# balanced so that they each take about the same amount of time.

# Note: We download Java 11.0.5 for a few reasons:
# - jcenter no longer allows https TLS1.0 connection (this is seen as
#   a gradle failed to download plugin error)
# - Travis has Java 11.0.2 baked in to it, 11.0.2 does not have a
#   recent patch (2019-10) to allow Java 11 to use a compatible version
#   of TLS.
# To overcome this situation, we emulate the travis 'install-jdk' script
# and install a latest Java 11. For reference:
#   https://sormuras.github.io/blog/2017-12-08-install-jdk-on-travis.html
# Java12 does not have this issue, we do not download the Java11 script
# for that JVM or else we would be overriding Java12 with Java11.  
#
# Additional note: The export commands seem to not apply when extracted
# to a script and seemingly only work when located in the main travis config
# here.
#

jobs:
  include:
    - stage: verify
      env: "Static Verification"
      jdk: openjdk11
      install: skip
      script:
        - JAVA_OPTS=-Xmx3G java -XX:+PrintFlagsFinal -version
        - free -m
